# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwstar < Formula
  desc ""
  homepage "https://github.com/georgepadayatti/jwstar"
  version "0.1.0"

  on_macos do
    url "https://github.com/georgepadayatti/jwstar/releases/download/v0.1.0/jwstar_0.1.0_darwin_all.tar.gz"
    sha256 "1353fe0918573999c5ad55bc2b6e53011bf1b2fb94706e29bc5a5a8599076c6b"

    def install
      bin.install "jwstar"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/georgepadayatti/jwstar/releases/download/v0.1.0/jwstar_0.1.0_linux_arm64.tar.gz"
      sha256 "50e4e9b739fe970cfa1a0c47477448e2188edefd3a0dacb0e747d1f82f9c196a"

      def install
        bin.install "jwstar"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/georgepadayatti/jwstar/releases/download/v0.1.0/jwstar_0.1.0_linux_amd64.tar.gz"
      sha256 "ed927f312ad98eef00d766b26b4ab263cfac005bdd56f6190ebcbbad1da2433e"

      def install
        bin.install "jwstar"
      end
    end
  end
end
